version: '3.9'

services:
  rbac:
    image: postgres:14.2-alpine
    restart: "no"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - rbac_volume:/var/lib/postgresql/data

volumes:
  rbac_volume:
